# Generated by Django 6.1 on 2026-08-18 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comidas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plato',
            name='disponible',
        ),
        migrations.AddField(
            model_name='plato',
            name='calorias',
            field=models.IntegerField(default=300, help_text='Número de calorías por porción'),
        ),
        migrations.AddField(
            model_name='plato',
            name='condicion_salud',
            field=models.CharField(blank=True, choices=[('diabetes', 'Diabetes'), ('hipertension', 'Hipertensión'), ('cáncer', 'Cáncer'), ('colesterol', 'Colesterol'), ('obesidad', 'Obesidad')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='plato',
            name='estilo_vida',
            field=models.CharField(blank=True, choices=[('deportista', 'Deportista'), ('vegano', 'Vegano'), ('flexible', 'Flexible'), ('vegetarianos', 'Vegetarianos'), ('keto', 'Alimento Keto'), ('hipocalorias', 'Alimentación Hipocalórica')], max_length=50, null=True),
        ),
    ]
