# Generated by Django 6.1 on 2026-08-18 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comidas', '0002_remove_plato_disponible_plato_calorias_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(help_text='Ej: Combo familiar que incluye 3 viandas a elección')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cantidad_platos', models.IntegerField(default=2, help_text='Número de comidas que incluye el combo')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='combos/')),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='recetas/')),
                ('ingredientes', models.TextField(help_text='Lista de ingredientes separados por líneas')),
                ('preparacion', models.TextField(help_text='Pasos de preparación')),
            ],
        ),
        migrations.RemoveField(
            model_name='plato',
            name='calorias',
        ),
        migrations.AddField(
            model_name='plato',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='platos/'),
        ),
        migrations.AlterField(
            model_name='plato',
            name='condicion_salud',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='plato',
            name='estilo_vida',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
