# Generated by Django 6.1 on 2026-08-19 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comidas', '0003_combo_receta_remove_plato_calorias_plato_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plato',
            name='tipo_plato',
            field=models.CharField(blank=True, choices=[('pollo', 'Pollo'), ('pescado', 'Pescado'), ('veggies', 'Veggies'), ('carne_roja', 'Carnes rojas')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='plato',
            name='condicion_salud',
            field=models.CharField(blank=True, choices=[('diabetes', 'Diabetes'), ('hipertension', 'Hipertensión'), ('higado_graso', 'Hígado graso'), ('colon_irritable', 'Colon irritable'), ('proteica', 'Proteica'), ('otras', 'Otras condiciones')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='plato',
            name='estilo_vida',
            field=models.CharField(blank=True, choices=[('vegano', 'Vegano'), ('vegetariano', 'Vegetariano'), ('keto', 'Keto')], max_length=50, null=True),
        ),
    ]
