# Generated by Django 6.1 on 2026-08-19 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comidas', '0004_plato_tipo_plato_alter_plato_condicion_salud_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuEspecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Menú Bajo en Carbohidratos, Menú Veggie', max_length=100)),
                ('descripcion', models.TextField(help_text='Listado de los platos que incluye este menú')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cantidad_platos', models.IntegerField(default=10, help_text='Número de viandas que incluye el menú')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='menus/')),
                ('envio_incluido', models.BooleanField(default=True, help_text='Marcar si este menú tiene envío sin cargo')),
            ],
        ),
        migrations.DeleteModel(
            name='Combo',
        ),
        migrations.AddField(
            model_name='plato',
            name='envio_incluido',
            field=models.BooleanField(default=False, help_text='Marcar si el precio ya incluye el envío sin costo'),
        ),
        migrations.AlterField(
            model_name='plato',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
