# Generated by Django 6.1 on 2026-08-19 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comidas', '0005_menuespecial_delete_combo_plato_envio_incluido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuespecial',
            name='precio_envio',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Costo del envío para este menú', max_digits=8),
        ),
        migrations.AddField(
            model_name='plato',
            name='precio_envio',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Costo del envío para este plato', max_digits=8),
        ),
    ]
