# Generated by Django 6.1 on 2026-08-19 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comidas', '0006_menuespecial_precio_envio_plato_precio_envio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuespecial',
            name='envio_incluido',
        ),
        migrations.RemoveField(
            model_name='plato',
            name='envio_incluido',
        ),
        migrations.AlterField(
            model_name='menuespecial',
            name='cantidad_platos',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='menuespecial',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='menuespecial',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='menuespecial',
            name='precio',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='menuespecial',
            name='precio_envio',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='plato',
            name='condicion_salud',
            field=models.CharField(blank=True, choices=[('diabetes', 'Diabetes'), ('hipertension', 'Hipertensión'), ('higado_graso', 'Hígado graso'), ('colon_irritable', 'Colon irritable'), ('proteica', 'Proteica'), ('otras', 'Otras')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='plato',
            name='precio',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='plato',
            name='precio_envio',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='receta',
            name='ingredientes',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='receta',
            name='preparacion',
            field=models.TextField(),
        ),
    ]
