# Generated by Django 6.1 on 2026-08-20 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comidas', '0007_remove_menuespecial_envio_incluido_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Viandas Empresariales o Viandas Infantiles', max_length=100)),
                ('descripcion', models.TextField(help_text='Descripción del servicio para el cliente')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='servicios/')),
                ('precio_base', models.DecimalField(decimal_places=0, default=0, help_text='Precio base o desde cuánto', max_digits=10)),
                ('precio_envio', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
            ],
        ),
    ]
